<?php
$pdf = new FPDF('P', 'in', [8.5, 8.5]);
$bookID = get_the_ID();
$bookMeta = get_post_meta($bookID, 'answers');
$answers = $bookMeta[0];
$pages = 18;
$terms = wp_get_object_terms($bookID, 'templates', array('fields' => 'all'));
$currentTerm = $terms[0];
$imgBG = esc_url(get_field('book_background_image', $currentTerm)['url']);
$imgBGArray = explode('?', $imgBG);
if (array_key_exists(0, $imgBGArray)) {
    $imgBG = $imgBGArray[0];
}


$kid = rtrim($answers['answer_0']['value']);
$pronoun = $answers['answer_1']['value'];
$sub = '';
$pos = '';
$was = '';
$obj = '';
$is = '';
switch ( $pronoun ) {
    case 'he/him/his':
        $sub = 'he';
        $obj = 'him';
        $pos = 'his';
        $was = 'was';
        $is  = 'is';
        $need = 'needs';
        break;
    case 'she/her/hers':
        $sub = 'she';
        $obj = 'her';
        $pos = 'hers';
        $was = 'was';
        $is  = 'is';
        $need = 'needs';
        break;
    case 'they/them/theirs':
        $sub = 'they';
        $obj = 'them';
        $pos = 'theirs';
        $was = 'where';
        $is  = 'are';
        $need = 'need';
        break;
}


$pacifier7_name 		                = $answers['answer_2']['value'];
$photo_child_using_a_pacifier			= $answers['answer_3']['value'];
$child_uses_a_pacifier			        = $answers['answer_4']['value'];
$photo_recent			                = $answers['answer_5']['value'];
$grownups			                    = $answers['answer_6']['value'];
$photo_snuggling        = $answers['answer_7']['value'];
$photo_favorite_doll 		= $answers['answer_8']['value'];
$photo_eating				= $answers['answer_9']['value'];
$photo_talking 		= $answers['answer_10']['value'];
$photo_giving_a_kiss 			= $answers['answer_11']['value'];
$photo_looking_relaxed 			= $answers['answer_12']['value'];
$photo_smiling	= $answers['answer_13']['value'];
$photoCover 			= $answers['answer_14']['value'];

$pdf->AddFont('ArialRoundedMT', 'B', 'arialroundedmtbold.php');
$pdf->AddPage();
$pdf->SetMargins(0.5, 3.8, 0.5);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
$pdf->SetFont('ArialRoundedMT', 'B', 27);
$text = $kid.' has used a '.$pacifier7_name.' since '.$sub.' '.$was.' a little baby.';
str_replace('â€™',"'",$text);
$pdf->MultiCell(0, 0.5, $text, 0, 'L');
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
centerImage($photo_child_using_a_pacifier, $pdf);
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->SetMargins(0.5, 3.2, 0.5);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
$text = $kid.' still uses a '.$pacifier7_name.' '.$child_uses_a_pacifier.' but '.$pos.' '.$is.' growing and getting too big for '.$pacifier7_name.'.';
str_replace('â€™',"'",$text);
$pdf->MultiCell(0, 0.5, $text, 0, 'L');
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
centerImage($photo_recent, $pdf);
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
$text = "It's easier to do big kid things without a $pacifier7_name. $kid $need $pos mouth to eat and drink. ";
str_replace('â€™',"'",$text);
$pdf->MultiCell(0, 0.5, $text, 0, 'L');
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
centerImage($photo_eating, $pdf);
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
$text = "$kid $need $pos mouth to talk, sing songs, and laugh. ";
str_replace('â€™',"'",$text);
$pdf->MultiCell(0, 0.5, $text, 0, 'L');
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
centerImage($photo_talking, $pdf);
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
$text = "$kid $need $pos mouth to give kisses, brush teeth, and blow bubbles. $kid is getting too big for a $pacifier7_name.";
str_replace('â€™',"'",$text);
$pdf->MultiCell(0, 0.5, $text, 0, 'L');
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
centerImage($photo_giving_a_kiss, $pdf);
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
$text = "It's hard to say bye-bye to a $pacifier7_name, but big kids can do hard things. And $kid has other ways to feel happy, calm, and safe. $kid can snuggle $grownups.";
str_replace('â€™',"'",$text);
$pdf->MultiCell(0, 0.5, $text, 0, 'L');
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
centerImage($photo_snuggling, $pdf);
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
$text = "$kid can squeeze $pos dolls and stuffies.";
str_replace('â€™',"'",$text);
$pdf->MultiCell(0, 0.5, $text, 0, 'L');
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
centerImage($photo_favorite_doll, $pdf);
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
$text = "$kid can close $pos eye and take deep breathes in and out, in and out. ";
str_replace('â€™',"'",$text);
$pdf->MultiCell(0, 0.5, $text, 0, 'L');
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
centerImage($photo_looking_relaxed, $pdf);
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
$text = "$kid does not need $pos $pacifier7_name anymore. $sub $is ready to say 'Bye-Bye, $pacifier7_name!'";
str_replace('â€™',"'",$text);
$pdf->MultiCell(0, 0.5, $text, 0, 'L');
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->SetFont('ArialRoundedMT','B',27);
$pdf->AddPage();
$pdf->Image($imgBG, 0, 0, 8.5, 8.5);
centerImage($photo_smiling, $pdf);
$pdf->SetFont('ArialRoundedMT','B',22);
$pdf->SetY(7.2);
$pdf->MultiCell(0, 0.5, $pdf->PageNo() - 1, 0, 'C');
$pdf->Output('i');
?>